### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by joeblew99** [ekke/ekkesBTLEexample#1]
Awesome example thanks so much ekkes !!

Are you using the same drawer and controls from your other github project ?

Also can't find where the calendar component is anywhere.
I am writing a calendar schedule component and planning to use your drawer project and it's common components as a base. 

Thanks again ekkes..:)

**Comment by ekke** [comment]
yes - I'm using similar Drawer and Controls in my other projects.
BTLE Example and QtWorldSummit app will always get the newest updates to this.
take a look at https://github.com/ekke/biz_data_x to see some examples of Calendar. Not all finished but will give you some ideas. Have used Calendar in other projects at customer sites - so biz_data_example is the newest opensource.

**Comment by joeblew99** [comment]
thanks. that helps and now i knwo where to look. cheers :)
